C ROUTINE: DREAD
C FUNCTION: THIS IS THE READ ROUTINE FOR FOR2D
C AUTHOR: AE
C DATE: 9/11/78
	SUBROUTINE DREAD (IREC,BUFFR,NREC,NELEM)
	COMMON /XFF2T/ ICHANN

	NBLK = NELEM/64
	IBLKN = NBLK*(IREC-1)
	IF (NREC.NE.1) NBLK=NBLK+NBLK
C	CALL RDB (ICHANN,IBLKN,BUFFR,NBLK)
	RETURN

	END
