C ROUTINE: DWRITE
C FUNCTION: THIS IS THE WRITE ROUTINE FOR FOR2D
C AUTHOR: AE
C DATE: 9/11/78
	SUBROUTINE DWRITE (IREC,BUFFR,NREC,NELEM)
	COMMON /XFF2T/ ICHANN

	NBLK = NELEM/64
	IBLKN = NBLK*(IREC-1)
	IF (NREC.NE.1) NBLK=NBLK+NBLK
C	CALL WRB (ICHANN,IBLKN,BUFFR,NBLK)
	RETURN

	END
