# Lexer common. This is necessary since the parser, generated by xyacc,
# does not allow any access to the lexer to initialize it, or to get
# variable values.

pointer	lex_line			# input line
int	lex_pos				# character position in line
char	lex_id[SZ_LINE]			# last identifier

common /lexcom/ lex_line, lex_pos, lex_id
