# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/icu-58.2-on-linux_64, last modified Thu Nov 16 04:14:02 2017
# ------------------------------------------------

package:
    name: icu
    version: '58.2'
source:
    fn: icu4c-58_2-src.tgz
    sha256: 2b0a4410153a9b20de0e20c7d8b66049a72aef244b53683d0d7521371683da0c
    url: http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz
build:
    number: '1'
    run_exports:
        - icu >=58.2,<59.0a0
    string: h9c2bf20_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_12
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hd763dfe_12
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h41d9e3f_12
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
    run:
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
test:
    commands:
        - test -f $PREFIX/lib/libicudata.a
        - test -f $PREFIX/lib/libicudata.so.58.2
        - test -f $PREFIX/lib/libicui18n.a
        - test -f $PREFIX/lib/libicui18n.so.58.2
        - test -f $PREFIX/lib/libicuio.a
        - test -f $PREFIX/lib/libicuio.so.58.2
        - test -f $PREFIX/lib/libicutest.a
        - test -f $PREFIX/lib/libicutest.so.58.2
        - test -f $PREFIX/lib/libicutu.a
        - test -f $PREFIX/lib/libicutu.so.58.2
        - test -f $PREFIX/lib/libicuuc.a
        - test -f $PREFIX/lib/libicuuc.so.58.2
        - genbrk --help
        - gencfu --help
        - gencnval --help
        - gendict --help
        - icuinfo --help
        - icu-config --help
        - makeconv gb-18030-2000.ucm
        - conda inspect linkages -p $PREFIX icu
    files:
        - de.txt
        - gb-18030-2000.ucm
about:
    description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

        Unicode and Globalization support for software applications. ICU is

        widely portable and gives applications the same results on all platforms

        and between C/C++ and Java software.

        '
    dev_url: http://source.icu-project.org/repos/icu/
    doc_url: http://site.icu-project.org/design
    home: http://site.icu-project.org/
    license: MIT
    summary: International Components for Unicode.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - msarahan
        - ocefpaf
