# This file created by conda-build 3.7.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libsodium-1.0.16-on-nwani-linux-64, last modified Tue Mar 27 17:26:27 2018
# ------------------------------------------------

package:
    name: libsodium
    version: 1.0.16
source:
    fn: libsodium-1.0.16.tar.gz
    sha256: eeadc7e1e1bcef09680fb4837d448fbdf57224978f865ac1c16745868fbd0533
    url: https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz
build:
    number: '0'
    run_exports:
        - libsodium >=1.0.16,<1.0.17.0a0
    string: h1bed415_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libstdcxx-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=7.2.0
test:
    commands:
        - test -f ${PREFIX}/include/sodium.h
        - test -f ${PREFIX}/lib/libsodium.a
        - test -f ${PREFIX}/lib/libsodium.so
about:
    description: 'Sodium is a new, easy-to-use software library for encryption, decryption,

        signatures, password hashing and more. It is a portable, cross-compilable,

        installable, packageable fork of NaCl, with a compatible API, and an

        extended API to improve usability even further. Its goal is to provide all

        of the core operations needed to build higher-level cryptographic tools.

        '
    dev_url: https://github.com/jedisct1/libsodium
    doc_url: https://download.libsodium.org/doc
    home: http://libsodium.org
    license: ISC
    license_file: LICENSE
    summary: A modern and easy-to-use crypto library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
