#!/usr/bin/env python
#
##
##	Flatfield.py:   		Stacking of individual datasets
##
##	Inputs: 		List of files generated by the identification
##	Outputs:		rmi_'Input'
##
##	Version 1.0: 		22/02/2011
##

#
# Import libraries
#



import sys
from pyraf import *
#import pyfits
import astropy.io.fits as pyfits
import numpy
from pyfits import getdata, getheader
iraf.images(_doprint=0)
iraf.immatch(_doprint=0)
#iraf.nmisc()
iraf.gemini(_doprint=0)
iraf.midir()
#
##
#### Removing bad chops-nods and preparing data
##
#
#
##
#### Creating FLATS
##
#
infile = sys.argv[1:2]
infile = infile[0]
file = open(infile,'r')
lines = file.readlines()

for line in lines:
	line = line.replace('\n','')
	line = line.replace(' ','')
	line = line.split(',')
	fileName = line[0]
	fileNameFlat = line[1]
	NNODS = int(line[2])
	NNODSETS = int(line[3])	
	NSAVSETS = int(line[4])
	print NNODS
	print fileName
	print fileNameFlat
	for j in range(1,NNODSETS*NNODS +1) :
		iraf.imarith('b_'+fileName+'['+str(j)+']',"/",'flat_'+fileNameFlat+'[1]',result='flp_n'+str(j)+'_'+fileName)
