#!/usr/bin/env python
#
##
##	Flatfield.py:   		Stacking of individual datasets
##
##	Inputs: 		List of files generated by the identification
##	Outputs:		rmi_'Input'
##
##	Version 1.0: 		22/02/2011
##

#
# Import libraries
#



import sys
from pyraf import *
import pyfits
import numpy
from pyfits import getdata, getheader
iraf.images(_doprint=0)
iraf.immatch(_doprint=0)
#iraf.nmisc()
iraf.noao(_doprint=0)
iraf.twodspec(_doprint=0)
iraf.longslit(_doprint=0)

infile = sys.argv[1:2]
infile = infile[0]
file = open(infile,'r')
lines = file.readlines()
for line in lines:
	line = line.replace('\n','')
	line = line.replace(' ','')
	line = line.split(',')
	fileName = line[0]
	fileName2 = fileName.split('.')
	fileName2 = fileName2[0]	
	av0= line[1]
	av1= line[2]
	print av0
	print av1
	iraf.aidpars.crpix = "1."
	iraf.aidpars.aidord= "3"
	iraf.aidpars.nfound= "3"
	iraf.aidpars.nbins= "20"
	iraf.aidpars.rms= "1"
	iraf.aidpars.fmatch= "0.7"	
	iraf.aidpars.reflist= "ref_list.dat"	
#	variable = iraf.aidpars.getParam('crpix',mode='h')
	print "Running autoidentify ... "
#	iraf.autoidentify(images='pl2_stck_'+fileName2 , crval=av0, cdelt = av1,fwidth =7., ftype='emission',cradius=10.,niterat=10.,section='middle line',coordlist='theoric_lines.dat',interact='YES',databas='database',nsum=60,functio='spline1',order=3,thresho=1.,minsep=2.,dbwrite='YES',overwrite='YES',verbose='YES')
	iraf.autoidentify(images='pl2_stck_'+fileName2 , crval=av0, cdelt = av1,fwidth =10., ftype='emission',cradius=5.,niterat=1.,section='middle line',coordlist='ref_list.dat',interact='YES',databas='database',nsum=60,functio='legendre',order=3,thresho=0.,minsep=8.,dbwrite='YES',overwrite='YES',verbose='YES')
	print "Running reidentify ... "
	iraf.reidentify(images='pl2_stck_'+fileName2, reference = 'pl2_stck_'+fileName2, coordlist='theoric_lines.dat',section='middle line', interact='NO', trace='no',nsum=10., step=10.,nlost=3, crval=av0, cdelt = av1,databas='database',thresho=0.,minsep=2.,verbose='yes')
	print "Running fitcoords ... "
	iraf.fitcoords(images='pl2_stck_'+fileName2,fitname='',xorder =2,yorder=3,deletions='',plotfile="plotfile",functio='legendre',database='database',interact="NO",combine='no')
	print "Running transform ... "
	iraf.transform(inp = 'pl2_stck_'+fileName2, output='wpl2_stck_'+fileName2,interp='linear',fitname='pl2_stck_'+fileName2,databas='database',dx="INDEF",x1="INDEF",x2="INDEF")
	iraf.transform(inp = 'pl1_stck_'+fileName2, output='wpl1_stck_'+fileName2,interp='linear',fitname='pl2_stck_'+fileName2,databas='database',dx="INDEF",x1="INDEF",x2="INDEF")
	iraf.transform(inp = 'pl3_stck_'+fileName2, output='wpl3_stck_'+fileName2,interp='linear',fitname='pl2_stck_'+fileName2,databas='database',dx="INDEF",x1="INDEF",x2="INDEF")
	iraf.transform(inp = 'pl4_stck_'+fileName2, output='wpl4_stck_'+fileName2,interp='linear',fitname='pl2_stck_'+fileName2,databas='database',dx="INDEF",x1="INDEF",x2="INDEF")
