# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cffi-1.12.2-python_3.7-on-linux_64, last modified Mon Mar 11 15:56:19 2019
# ------------------------------------------------

package:
    name: cffi
    version: 1.12.2
source:
    patches:
        - 0001-Link-to-dl-library.patch
        - setup-linux.patch
    sha256: e113878a446c6228669144ae8a56e268c91b7f1fafae927adc4879d9849e0ea7
    url: https://pypi.io/packages/source/c/cffi/cffi-1.12.2.tar.gz
build:
    number: '1'
    script: /tmp/build/80754af9/cffi_1552319893558/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py37h2e261b9_1
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1b h7b6447c_1
        - pip 19.0.3 py37_0
        - pycparser 2.19 py37_0
        - python 3.7.2 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.3.0
        - pycparser
        - python >=3.7,<3.8.0a0
test:
    imports:
        - _cffi_backend
        - cffi
    requires:
        - openssl
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - mingwandroid
        - ocefpaf
