# This file created by conda-build 3.8.0
# ------------------------------------------------

package:
    name: gstreamer
    version: 1.14.0
source:
    -   sha256: fc361367f0d4b780a868a8833f9f30b9c9f4ac9faea4e6b251db8b4b0398466e
        url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.14.0.tar.xz
    -   folder: plugins_base
        sha256: 7e904660ff56e02b036cf7fdfb77a50a540828ca9d2614d69ba931772e5b6940
        url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.14.0.tar.xz
build:
    activate_in_script: true
    number: 1
    run_exports:
        - gstreamer >=1.14.0,<1.15.0a0
    string: hb453b48_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - bison 3.0.4 h2db1b24_1
        - flex 2.6.4 ha10e3a4_1
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.0 hae598fd_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - ca-certificates 2018.03.07 0
        - cairo 1.14.12 h7636065_2
        - fontconfig 2.12.6 h49f89f6_0
        - freetype 2.8 hab7d2ae_1
        - glib 2.56.1 h000015b_0
        - gobject-introspection 1.56.1 py36h085f2ab_0
        - icu 58.2 h9c2bf20_1
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.8 hf84eae3_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2o h20670df_0
        - pcre 8.42 h439df22_0
        - pixman 0.34.0 hceecf20_3
        - python 3.6.5 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - glib >=2.56.1,<2.57.0a0
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.2.0
        - pcre >=8.42,<9.0a0
        - xz >=5.2.3,<6.0a0
test:
    commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
about:
    doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/docs
    summary: Library for constructing graphs of media-handling components
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: gstreamer_and_plugins
        path: /tmp/build/80754af9/rsync-recipes/gstreamer_and_plugins-1.14.0-on-linux_64
        version: 1.14.0
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - msarahan
