# This file created by conda-build 3.8.0
# ------------------------------------------------

package:
    name: gst-plugins-base
    version: 1.14.0
source:
    -   sha256: fc361367f0d4b780a868a8833f9f30b9c9f4ac9faea4e6b251db8b4b0398466e
        url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.14.0.tar.xz
    -   folder: plugins_base
        sha256: 7e904660ff56e02b036cf7fdfb77a50a540828ca9d2614d69ba931772e5b6940
        url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.14.0.tar.xz
build:
    activate_in_script: true
    number: 1
    run_exports:
        - gst-plugins-base >=1.14.0,<1.15.0a0
    string: hbbd80ab_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 26
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libdrm-devel-cos6-x86_64 2.4.65 h5701c1a_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxdamage-cos6-x86_64 1.1.3 h8e310ee_0
        - libxdamage-devel-cos6-x86_64 1.1.3 0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxfixes-cos6-x86_64 5.0.3 h3a64028_0
        - libxfixes-devel-cos6-x86_64 5.0.3 0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - libxxf86vm-cos6-x86_64 1.1.3 h3cd9653_0
        - libxxf86vm-devel-cos6-x86_64 1.1.3 0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
        - mesa-libgl-devel-cos6-x86_64 11.0.7 h5a2c0ac_0
        - perl 5.26.0 hae598fd_0
        - pkg-config 0.29.2 h1bed415_8
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - glib 2.56.1 h000015b_0
        - gstreamer >=1.14.0,<2.0a0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libxcb 1.13 h1bed415_1
        - pcre 8.42 h439df22_0
        - pthread-stubs 0.3 h0ce48e5_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - glib >=2.56.1,<2.57.0a0
        - gstreamer >=1.14.0,<2.0a0
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - libxcb >=1.13,<2.0a0
        - xz >=5.2.3,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f $PREFIX/lib/libgstallocators-1.0.so
        - test -f $PREFIX/lib/libgstapp-1.0.so
        - test -f $PREFIX/lib/libgstaudio-1.0.so
        - test -f $PREFIX/lib/libgstfft-1.0.so
        - test -f $PREFIX/lib/libgstpbutils-1.0.so
        - test -f $PREFIX/lib/libgstriff-1.0.so
        - test -f $PREFIX/lib/libgstrtp-1.0.so
        - test -f $PREFIX/lib/libgstrtsp-1.0.so
        - test -f $PREFIX/lib/libgstsdp-1.0.so
        - test -f $PREFIX/lib/libgsttag-1.0.so
        - test -f $PREFIX/lib/libgstvideo-1.0.so
about:
    description: 'GStreamer Base Plug-ins is a well-groomed and well-maintained collection
        of

        GStreamer plug-ins and elements, spanning the range of possible types of

        elements one would want to write for GStreamer.

        '
    doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs
    summary: GStreamer Base Plug-ins
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: gstreamer_and_plugins
        path: /tmp/build/80754af9/rsync-recipes/gstreamer_and_plugins-1.14.0-on-linux_64
        version: 1.14.0
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - msarahan
