# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/gmp-6.1.2-on-linux_64, last modified Mon Nov 13 21:43:18 2017
# ------------------------------------------------

package:
    name: gmp
    version: 6.1.2
source:
    fn: gmp-6.1.2.tar.bz2
    sha256: 5275bb04f4863a13516b2f39392ac5e272f5e1bb8057b18aec1c9b79d73d8fb2
    url: https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2
build:
    number: '1'
    run_exports:
        - gmp >=6.1.2
    string: h6c8ec71_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_11
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h4118e58_11
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h5e79354_11
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - m4 1.4.18 h4e445db_0
    run:
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
test:
    commands:
        - test -f ${PREFIX}/lib/libgmp.a
        - test -f ${PREFIX}/lib/libgmp.so
        - test -f ${PREFIX}/lib/libgmpxx.a
        - test -f ${PREFIX}/lib/libgmpxx.so
    files:
        - test.c
    requires:
        - gcc_linux-64
about:
    home: http://gmplib.org/
    license: GPL 2 and LGPL 3
    license_file: COPYING.LESSERv3
    summary: The GNU multiprecision library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - isuruf
        - jakirkham
