grep STDQLMRE  *.x
grep NSTDQLM  *.x
grep NTIMES  *.x
grep TIMESREC  *.x
grep XS-TIMES  *.x
grep  DEFATTR1   *.x
grep  POISSERR    *.x
grep  XS-INDXX   *.x
grep  XS-INDXY   *.x
grep  CHECKSUM  *.x
grep  DATASUM   *.x
grep  XS-STDQL   *.x
grep  ALLQLM    *.x
grep  XS-ALLQL    *.x
grep  ALLQLMRE  *.x
